package jdbc.model;

import java.sql.SQLException;
import java.sql.Statement;

/**
 * 保存要执行的Statement方法名称,用于在多个Statement实例上循环执行
 * Created by aude on 2016/12/21.
 */
public enum ExecuteMethod {
    /*----------------------------------Statement方法---------------------*/
    execute_sql,
    execute_sql_autoGeneratedKeys,
    execute_sql_columnIndexes,
    execute_sql_columnNames,

    executeQuery_sql,

    executeUpdate_sql,
    executeUpdate_sql_autoGeneratedKeys,
    executeUpdate_sql_columnIndexes,
    executeUpdate_sql_columnNames,

    /*------------------------------TPreparedStatement方法-----------------*/
    execute;

    public static enum MethodReturnType {
        int_type,
        boolean_type,
        result_set_type;
    }

    public MethodReturnType getReturnType() {
        switch (this) {
            case execute_sql:
            case execute_sql_autoGeneratedKeys:
            case execute_sql_columnIndexes:
            case execute_sql_columnNames:
            case execute:
                return MethodReturnType.boolean_type;
            default:


        }
    }

    public Object executeMethod(Statement stmt, Object... args) throws SQLException {

    }
}
